# Generated by Django 2.0.5 on 2018-06-17 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20180610_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='users',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
