# Generated by Django 2.0.6 on 2018-06-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180617_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_subscribers_+', to='profiles.Profile'),
        ),
    ]
