# Generated by Django 2.1.1 on 2018-09-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180618_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.CharField(choices=[('1', 'Активный'), ('2', 'Удаленный'), ('3', 'Заблокированный')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
