# Generated by Django 2.1.1 on 2018-10-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_', '0003_auto_20180923_1505'),
        ('profiles', '0011_auto_20180918_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(default=2732, on_delete=django.db.models.deletion.CASCADE, to='cities_.CityTable'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
