# Generated by Django 2.1.1 on 2018-10-27 18:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20181023_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribe', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
            options={
                'verbose_name': 'Подписчики',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='profilesubscribers',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_p', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='profilesubscribers',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_p', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='through_profile',
            field=models.ManyToManyField(through='profiles.ProfileSubscribers', to='profiles.Profile'),
        ),
    ]
