# Generated by Django 2.1.1 on 2018-09-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityTable',
            fields=[
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('city_id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
