# Generated by Django 2.1.1 on 2018-09-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_', '0002_auto_20180923_1320'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='citytable',
            table='city_table',
        ),
    ]
