# Generated by Django 2.0.5 on 2018-05-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_id', models.IntegerField()),
                ('important', models.BooleanField()),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('area_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('region_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=150, null=True)),
                ('area_ua', models.CharField(blank=True, max_length=150, null=True)),
                ('region_ua', models.CharField(blank=True, max_length=150, null=True)),
                ('title_be', models.CharField(blank=True, max_length=150, null=True)),
                ('area_be', models.CharField(blank=True, max_length=150, null=True)),
                ('region_be', models.CharField(blank=True, max_length=150, null=True)),
                ('title_en', models.CharField(blank=True, max_length=150, null=True)),
                ('area_en', models.CharField(blank=True, max_length=150, null=True)),
                ('region_en', models.CharField(blank=True, max_length=150, null=True)),
                ('title_es', models.CharField(blank=True, max_length=150, null=True)),
                ('area_es', models.CharField(blank=True, max_length=150, null=True)),
                ('region_es', models.CharField(blank=True, max_length=150, null=True)),
                ('title_pt', models.CharField(blank=True, max_length=150, null=True)),
                ('area_pt', models.CharField(blank=True, max_length=150, null=True)),
                ('region_pt', models.CharField(blank=True, max_length=150, null=True)),
                ('title_de', models.CharField(blank=True, max_length=150, null=True)),
                ('area_de', models.CharField(blank=True, max_length=150, null=True)),
                ('region_de', models.CharField(blank=True, max_length=150, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('area_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('region_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('title_it', models.CharField(blank=True, max_length=150, null=True)),
                ('area_it', models.CharField(blank=True, max_length=150, null=True)),
                ('region_it', models.CharField(blank=True, max_length=150, null=True)),
                ('title_pl', models.CharField(blank=True, max_length=150, null=True)),
                ('area_pl', models.CharField(blank=True, max_length=150, null=True)),
                ('region_pl', models.CharField(blank=True, max_length=150, null=True)),
                ('title_ja', models.CharField(blank=True, max_length=150, null=True)),
                ('area_ja', models.CharField(blank=True, max_length=150, null=True)),
                ('region_ja', models.CharField(blank=True, max_length=150, null=True)),
                ('title_lt', models.CharField(blank=True, max_length=150, null=True)),
                ('area_lt', models.CharField(blank=True, max_length=150, null=True)),
                ('region_lt', models.CharField(blank=True, max_length=150, null=True)),
                ('title_lv', models.CharField(blank=True, max_length=150, null=True)),
                ('area_lv', models.CharField(blank=True, max_length=150, null=True)),
                ('region_lv', models.CharField(blank=True, max_length=150, null=True)),
                ('title_cz', models.CharField(blank=True, max_length=150, null=True)),
                ('area_cz', models.CharField(blank=True, max_length=150, null=True)),
                ('region_cz', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': '_cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_ru', models.CharField(blank=True, max_length=60, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=60, null=True)),
                ('title_be', models.CharField(blank=True, max_length=60, null=True)),
                ('title_en', models.CharField(blank=True, max_length=60, null=True)),
                ('title_es', models.CharField(blank=True, max_length=60, null=True)),
                ('title_pt', models.CharField(blank=True, max_length=60, null=True)),
                ('title_de', models.CharField(blank=True, max_length=60, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=60, null=True)),
                ('title_it', models.CharField(blank=True, max_length=60, null=True)),
                ('title_pl', models.CharField(blank=True, max_length=60, null=True)),
                ('title_ja', models.CharField(blank=True, max_length=60, null=True)),
                ('title_lt', models.CharField(blank=True, max_length=60, null=True)),
                ('title_lv', models.CharField(blank=True, max_length=60, null=True)),
                ('title_cz', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': '_countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_id', models.IntegerField()),
                ('title_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=150, null=True)),
                ('title_be', models.CharField(blank=True, max_length=150, null=True)),
                ('title_en', models.CharField(blank=True, max_length=150, null=True)),
                ('title_es', models.CharField(blank=True, max_length=150, null=True)),
                ('title_pt', models.CharField(blank=True, max_length=150, null=True)),
                ('title_de', models.CharField(blank=True, max_length=150, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('title_it', models.CharField(blank=True, max_length=150, null=True)),
                ('title_pl', models.CharField(blank=True, max_length=150, null=True)),
                ('title_ja', models.CharField(blank=True, max_length=150, null=True)),
                ('title_lt', models.CharField(blank=True, max_length=150, null=True)),
                ('title_lv', models.CharField(blank=True, max_length=150, null=True)),
                ('title_cz', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': '_regions',
                'managed': False,
            },
        ),
    ]
