# Generated by Django 2.1.1 on 2018-09-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityTable',
            fields=[
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('city_id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
