# Generated by Django 2.1.1 on 2018-09-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_citytable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citytable',
            options={},
        ),
    ]
