# Generated by Django 2.0.5 on 2018-05-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0002_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='subscriber_id',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='user_id',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='custom_profile.Profile'),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='users',
            field=models.ManyToManyField(to='custom_profile.Profile'),
        ),
    ]
