# Generated by Django 2.0.5 on 2018-05-19 04:17

from django.db import migrations, models
from events_all import helper


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0003_auto_20180512_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_name', models.TextField(blank=True, max_length=50)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=helper.upload_to)),
                ('users', models.ManyToManyField(to='custom_profile.Profile')),
            ],
        ),
    ]
