# Generated by Django 2.0.5 on 2018-05-20 03:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import helper


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профили', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='profile_avatar',
            options={'verbose_name': 'Аватары', 'verbose_name_plural': 'Аватары'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Подписчики', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.RemoveField(
            model_name='profile_avatar',
            name='hash_name',
        ),
        migrations.RemoveField(
            model_name='profile_avatar',
            name='users',
        ),
        migrations.AddField(
            model_name='profile_avatar',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='custom_profile.Profile'),
        ),
        migrations.AlterField(
            model_name='profile_avatar',
            name='image',
            field=models.ImageField(default='media/avatar/default/img.jpg', upload_to=helper.upload_to),
        ),
        migrations.AlterField(
            model_name='profile_avatar',
            name='last_update',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
