# Generated by Django 2.0.5 on 2018-05-20 16:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helper


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_profile', '0005_auto_20180520_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('image', models.ImageField(default='avatar/default/img.png', upload_to=helper.upload_to)),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аватары',
                'verbose_name_plural': 'Аватары',
            },
        ),
        migrations.RemoveField(
            model_name='profile_avatar',
            name='user',
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile_avatar',
        ),
    ]
