# Generated by Django 2.0.5 on 2018-05-22 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_profile', '0006_auto_20180520_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(choices=[('1', 'Открыть сообщения для всех'), ('2', 'Написать могут только те, на кого я подписан'), ('3', 'Закрыть сообщения для всех')], default=1, max_length=2)),
                ('birth_date', models.CharField(choices=[('1', 'Видно всем'), ('2', 'Видно только подписчикам'), ('3', 'Скрыть для всех')], default=1, max_length=2)),
                ('invite', models.CharField(choices=[('1', 'Приглашать могут все'), ('2', 'Приглашать могут только те, на кого я подписан ')], default=1, max_length=2)),
                ('near_invite', models.CharField(choices=[('1', 'Включено'), ('2', 'Выключено')], default=1, max_length=2)),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользовательские настройки',
                'verbose_name_plural': 'Пользовательские настройки',
            },
        ),
    ]
