# Generated by Django 2.0.5 on 2018-05-27 14:09

from django.db import migrations, models
from events_all import helper


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0007_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileavatar',
            name='reduced_image',
            field=models.ImageField(default='avatar/default/img.png', upload_to=helper.upload_to),
        ),
    ]
