# Generated by Django 2.0.5 on 2018-05-28 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0008_profileavatar_reduced_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileavatar',
            name='reduced_image',
        ),
    ]
