# Generated by Django 2.0.5 on 2018-06-10 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('1', 'Открытая'), ('2', 'Закрытая')], default=1, max_length=2)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='GroupSubscribers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='groups.Group')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписчики группы',
                'verbose_name_plural': 'Подписчики группы',
            },
        ),
    ]
