# Generated by Django 2.0.6 on 2018-06-19 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='inviter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='profiles.Profile'),
        ),
    ]
