# Generated by Django 2.0.6 on 2018-06-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180619_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allroles',
            options={'verbose_name': 'Роли участников группы', 'verbose_name_plural': 'Роли участников группы'},
        ),
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
    ]
