# Generated by Django 2.0.6 on 2018-06-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20180619_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Подписчики группы', 'verbose_name_plural': 'Подписчики группы'},
        ),
        migrations.RemoveField(
            model_name='membership',
            name='invite_reason',
        ),
    ]
