# Generated by Django 2.0.6 on 2018-06-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_allroles_ru_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='groups.AllRoles'),
        ),
    ]
