# Generated by Django 2.0.6 on 2018-06-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20180619_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
