# Generated by Django 2.0.6 on 2018-06-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20180620_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
