# Generated by Django 2.1b1 on 2018-08-27 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import events_all.helper


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20180620_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('image', models.ImageField(default='avatar/default/img.jpg',
                                            upload_to=events_all.helper.ImageHelper.upload_to)),
            ],
            options={
                'verbose_name': 'Аватары группы',
                'verbose_name_plural': 'Аватары группы',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.CharField(choices=[('1', 'Активная'), ('2', 'Удаленная'), ('3', 'Заблокированная')],
                                   default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='groupavatar',
            name='group',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
