# Generated by Django 2.0.5 on 2018-05-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0002_auto_20180516_1112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparty',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='eventparty',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='eventparty',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='EventParty',
        ),
    ]
