# Generated by Django 2.0.5 on 2018-06-07 07:22

from django.db import migrations, models

from events_all import helper


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0005_event_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event_avatar',
            name='image',
            field=models.ImageField(default='avatar_event/default/img.jpg', upload_to=helper.ImageHelper.upload_to),
        ),
    ]
