# Generated by Django 2.0.5 on 2018-06-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('events_', '0009_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
