# Generated by Django 2.0.5 on 2018-06-20 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0010_event_created_by_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
