# Generated by Django 2.0.5 on 2018-06-20 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_', '0011_auto_20180620_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('news_crearor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_.Event')),
            ],
        ),
    ]
