# Generated by Django 2.1b1 on 2018-07-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0012_eventnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventnews',
            old_name='news_crearor',
            new_name='news_creator',
        ),
    ]
