# Generated by Django 2.1b1 on 2018-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0014_eventnews_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
