# Generated by Django 2.1.1 on 2018-09-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0016_auto_20180923_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
