# Generated by Django 2.1.1 on 2018-09-28 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20180918_1653'),
        ('events_', '0016_auto_20180923_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'Подписчики события',
                'verbose_name_plural': 'Подписчики события',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(through='events_.Event_Membership', to='profiles.Profile'),
        ),
    ]
