# Generated by Django 2.1.1 on 2018-09-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0017_auto_20180928_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategoryRelatiom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_.EventCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='eventcategoryrelatiom',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(through='events_.EventCategoryRelatiom', to='events_.EventCategory'),
        ),
    ]
