# Generated by Django 2.1.1 on 2018-09-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0018_auto_20180928_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
