# Generated by Django 2.1.1 on 2018-09-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0019_eventgeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='geo_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events_.EventGeo'),
        ),
    ]
