# Generated by Django 2.1.1 on 2018-09-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0020_event_geo_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventCategoryRelatiom',
            new_name='EventCategoryRelation',
        ),
    ]
