# Generated by Django 2.1.1 on 2018-09-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20180918_1653'),
        ('events_', '0021_auto_20180929_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Membership',
            new_name='EventMembership',
        ),
    ]
