# Generated by Django 2.1.1 on 2018-10-22 16:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import events_all.helper


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20180827_1701'),
        ('events_', '0022_auto_20180929_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'События', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Категории событий', 'verbose_name_plural': 'Категории событий'},
        ),
        migrations.AlterModelOptions(
            name='eventcategoryrelation',
            options={'verbose_name': 'Связка Категории событий', 'verbose_name_plural': 'Связка Категории событий'},
        ),
        migrations.AlterModelOptions(
            name='eventgeo',
            options={'verbose_name': 'Гео меметки', 'verbose_name_plural': 'Гео метки'},
        ),
        migrations.AlterModelOptions(
            name='eventnews',
            options={'verbose_name': 'Новости событий', 'verbose_name_plural': 'Новости событий'},
        ),
        migrations.AlterModelOptions(
            name='eventstatus',
            options={'verbose_name': 'Статус события', 'verbose_name_plural': 'Статус события'},
        ),
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.CharField(choices=[('1', 'Активный'), ('2', 'Закрытый'), ('3', 'Удаленный'), ('4', 'Заблокированный')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 22, 16, 48, 44, 134845, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='eventnews',
            name='news_group',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventnews',
            name='news_creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventnews',
            name='news_event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events_.Event'),
        ),
        migrations.AlterField(
            model_name='eventnews',
            name='news_image',
            field=models.ImageField(default='avatar_event/default/img.jpg', upload_to=events_all.helper.ImageHelper.upload_to),
        ),
    ]
