# Generated by Django 2.1.1 on 2018-10-22 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0023_auto_20181022_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 22, 16, 49, 6, 749140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventnews',
            name='news_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
