# Generated by Django 2.1.1 on 2018-10-24 06:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events_', '0027_auto_20181024_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 24, 6, 25, 10, 93107, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventlikes',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
