# Generated by Django 2.1.1 on 2018-10-27 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0009_auto_20180827_1701'),
        ('events_', '0028_auto_20181024_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmembership',
            name='role',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='event_role', to='groups.AllRoles'),
        ),
        migrations.AddField(
            model_name='eventviews',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventlikes',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventlikes',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='eventviews',
            unique_together={('event', 'user')},
        ),
    ]
